[package]
name = "himalaya"
description = "CLI to manage your emails."
version = "0.7.3"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-interface", "command-line-utilities", "email"]
keywords = ["cli", "mail", "email", "client", "imap"]
homepage = "https://pimalaya.org/himalaya/"
documentation = "https://pimalaya.org/himalaya/"
repository = "https://github.com/soywod/himalaya"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["rustls-tls", "rustls-native-certs", "imap-backend", "smtp-sender"]

# rustls
rustls-tls = ["pimalaya-email/rustls-tls"]
rustls-native-certs = ["pimalaya-email/rustls-native-certs"]

# native tls
native-tls = ["pimalaya-email/native-tls"]
native-tls-vendored = ["pimalaya-email/native-tls-vendored"]

# backends
imap-backend = ["pimalaya-email/imap-backend"]
notmuch-backend = ["pimalaya-email/notmuch-backend"]

# senders
smtp-sender = ["pimalaya-email/smtp-sender"]

[dev-dependencies]
tempfile = "3.3"

[dependencies]
anyhow = "1.0"
atty = "0.2"
chrono = "0.4.24"
clap = "4.0"
clap_complete = "4.0"
clap_mangen = "0.2"
console = "0.15.2"
dialoguer = "0.10.2"
dirs = "4.0.0"
email_address = "0.2.4"
env_logger = "0.8"
erased-serde = "0.3"
indicatif = "0.17"
log = "0.4"
once_cell = "1.16.0"
pimalaya-email = { git = "https://git.sr.ht/~soywod/pimalaya" }
pimalaya-keyring = { git = "https://git.sr.ht/~soywod/pimalaya" }
pimalaya-process = { git = "https://git.sr.ht/~soywod/pimalaya" }
pimalaya-secret = { git = "https://git.sr.ht/~soywod/pimalaya" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "2.1"
termcolor = "1.1"
terminal_size = "0.1"
toml = "0.7.2"
unicode-width = "0.1"
url = "2.2"
uuid = { version = "0.8", features = ["v4"] }
